<?php
return [
	'AutoloadMapBuilder' => 'classes/system/autoload',
	'AutoloadMap' => 'classes/system/autoload',

	'AbstractApplication' => 'classes/system/app',
	'Application' => 'classes/system/app',
	'ConsoleApplication' => 'classes/system/app',

	'ApplicationTool' => 'classes/system/app',
	'ApplicationConductor' => 'classes/system/app',
	'ApplicationComponent' => 'classes/system/app',
	'ApplicationLogger' => 'classes/system/app',
	'ComponentList' => 'classes/system/app',
	'Dialog' => 'classes/system/app',
	'Router' => 'classes/system/app',
	'AjaxRouter' => 'classes/system/app',
	'Response' => 'classes/system/app',
	'ResponseSource' => 'classes/system/app',
	'User' => 'classes/system/app',

	'Console' => 'classes/system',
	'HtmlHead' => 'classes/system',
	'JsCompiler' => 'classes/system/JsCompiler',
	'JsCompileDependencies' => 'classes/system/JsCompiler',
	'NodeJsExecutor' => 'classes/system/JsCompiler',
	'PluginEditor' => 'classes/system/editor',
	'ServiceEditor' => 'classes/system/editor',

	'Language' => 'classes/i18n',
	'I18nMap' => 'classes/i18n',
	'I18nApplicationMap' => 'classes/i18n',
	'I18nServiceMap' => 'classes/i18n',
	'I18nPluginMap' => 'classes/i18n',

	'PackageDirectory' => 'classes/package',
	'PackageBrowser' => 'classes/package',
	'ServicesMap' => 'classes/package',
	'Service' => 'classes/package',
	'ServiceRouter' => 'classes/package',
	'ServiceController' => 'classes/package',
	'ServiceConductor' => 'classes/package',
	'ServiceMigrationMap' => 'classes/package/system',

	'PluginDirectory' => 'classes/plugin',
	'PluginBrowser' => 'classes/plugin',
	'Snippet' => 'classes/plugin',
	'Plugin' => 'classes/plugin',
	'PluginConductor' => 'classes/plugin',
	'Respondent' => 'classes/plugin',
	'PluginBuildContext' => 'classes/plugin/build',
	'SnippetBuildContext' => 'classes/plugin/build',
	'SnippetCacheData' => 'classes/plugin/build',

	'Model' => 'classes/model',
	'ModelBrowser' => 'classes/model',
	'ModelData' => 'classes/model',
	'ModelManager' => 'classes/model',
	'ModelProvider' => 'classes/model',
	'ModelSchema' => 'classes/model',
	'ModelField' => 'classes/model/field',
	'ModelFieldString' => 'classes/model/field',
	'ModelFieldInteger' => 'classes/model/field',
	'ModelFieldBoolean' => 'classes/model/field',
	'ModelFieldTimestamp' => 'classes/model/field',
	'ModelFieldRelation' => 'classes/model/field',
	'CrudAdapter' => 'classes/model/CRUD',
	'DbCrudAdapter' => 'classes/model/CRUD',

	'JsModuleMapBuilder' => 'classes/module',
	'JsModuleMap' => 'classes/module',

	'MigrationMap' => 'classes/system/migration',
	'MigrationManager' => 'classes/system/migration',
	'ModelMigrateExecutor' => 'classes/system/migration',
	'MigrationMaker' => 'classes/system/migration',

	'DataObject' => 'classes/dataClasses',

	'DbColumnDefinition' => 'classes/db',
	'DbTableSchemaProvider' => 'classes/db',
	'DbTable' => 'classes/db',
	'DbRecord' => 'classes/db',
	'DbConnectionList' => 'classes/db',
	'DB' => 'classes/db',
	'DBpostgres' => 'classes/db',
	'DBmysql' => 'classes/db',

	'Request' => 'classes/tools',
	'Vector' => 'classes/tools',
	'Collection' => 'classes/tools',
	'Tree' => 'classes/tools',

	'BaseFile' => 'classes/file',
	'File' => 'classes/file',
	'Directory' => 'classes/file',
	'YamlFile' => 'classes/file',
	'HtmpFile' => 'classes/file',
	'ConfigFile' => 'classes/file',

	'Cli' => 'classes/system/cli',
	'CliProcessor' => 'classes/system/cli',

	'BitLine' => 'classes/bit',
	'BitMap' => 'classes/bit',

	'ConfigHelper' => 'classes/helpers',
	'ClassHelper' => 'classes/helpers',
	'ModuleHelper' => 'classes/helpers',
	'Math' => 'classes/helpers',
	'ArrayHelper' => 'classes/helpers',
	'StringHelper' => 'classes/helpers',
	'Geom' => 'classes/helpers',
	'Yaml' => 'classes/helpers',
	'Htmp' => 'classes/helpers',
	'WidgetHelper' => 'classes/helpers',
	'I18nHelper' => 'classes/helpers',

	'IndentData' => '../widgets/Box/positioningStrategiesPhp',
	'PositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',
	'SimplePositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',
	'AlignPositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',
	'StreamPositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',
	'GridPositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',
	'SlotPositioningStrategy' => '../widgets/Box/positioningStrategiesPhp',

	'ClassOfServiceInterface' => 'interfaces',
	'AuthenticationInterface' => 'interfaces',
	'AuthorizationInterface' => 'interfaces',
	'LoggerInterface' => 'interfaces',

	'ClassOfServiceTrait' => 'traits',

	'ContextTreeInterface' => 'traits',
	'ContextTreeTrait' => 'traits',
];